---
services:
  vc-data-model-v2:
    build: https://github.com/w3c/vc-data-model-2.0-test-suite.git#allure-in-docker
    entrypoint: ["./run.sh"]
    volumes:
      - ./run.sh:/test-suite/run.sh
      - ./localConfig.cjs:/test-suite/localConfig.cjs
    labels:
      - traefik.enable=true
      - traefik.http.routers.vc-data-model.rule=Host(`vc-data-model.docker.localhost`)
      - traefik.http.routers.vc-data-model.entrypoints=web
      - traefik.http.services.vc-data-model.loadbalancer.server.port=8000

  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro